config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get '/about', to: 'pages#about'

  resources :prescriptions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  validates :description, presence: true, length: {minimum: 3}
  validates :prescriptionType, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
    
    def about
    end

end 

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController

  before_action :set_prescription, only: [:edit, :update, :show, :destroy]

  def index
  @prescriptions = Prescription.all
  end

  def new
    @prescription = Prescription.new
  end

  def create
    @prescription = Prescription.new(prescription_params)
    if @prescription.save
      flash[:notice] = "Prescription was successfully created"
      redirect_to prescription_path(@prescription)
    else
      render 'new' 
    end
  end

  def show
  end

  def edit
  end

  def update 
    if @prescription.update(prescription_params)
      flash[:notice] = "Prescription was successfully edited"
      redirect_to prescription_path(@prescription)
    else
      render 'new' 
    end
  end

  def destroy
    @prescription.destroy
    flash[:notice] = "Prescription successfully deleted"
    redirect_to prescriptions_path
  end
  
  private
  def set_prescription
    @prescription = Prescription.find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(:prescriptionType, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/partials/messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_messages.html.erb
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg%></li>
      </ul>
    <%end%>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>home page</h1>

<%= link_to 'Prescriptions Management', prescriptions_path %> | <%= link_to 'About', about_path %>

app/views/prescriptions/edit.html.erb
<h1>Edit prescription</h1>

<%= render 'prescriptions/partials/form' %>

<%= link_to "Back", prescriptions_path%>

app/views/prescriptions/index.html.erb
<h1>List of Prescriptions</h1>

<p>
  <%= link_to "Create prescription", new_prescription_path %>
</p>

<table>
  <tr>
    <th>Id</th>
    <th>Type</th>
    <th>Description</th>
  </tr>
  <% @prescriptions.each do |p| %>
    <tr>
      <td><%= p.id%></td>
      <td><%= p.prescriptionType%></td>
      <td><%= p.description%></td>
      <td><%= link_to "Edit", edit_prescription_path(p) %></td>
      <td><%= link_to "View", prescription_path(p) %></td>
      <td><%= link_to "Delete", prescription_path(p), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
<table>

app/views/prescriptions/new.html.erb
<h1>Create a new prescription</h1>

<%= render 'prescriptions/partials/form' %>

<%= link_to "Back", prescriptions_path%>

app/views/prescriptions/partials/_form.html.erb
<% if @prescription.errors.any? %>
<h3>The following errors prevented description to be created</h3>
  <ul>
    <% @prescription.errors.full_messages.each do |msg| %>
      <li>
      <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @prescription do |p| %>

  <p>
    <%= p.label 'Prescription Type' %> <br />
    <%= p.text_field :prescriptionType %>
  </p>

  <p>
    <%= p.label :description %> <br />
    <%= p.text_area :description %>
  </p>

  <p>
    <%= p.submit :submit %>
  </p>

<%end%>

app/views/prescriptions/show.html.erb
<h1>Prescription</h1>
<p>
  Type: <%= @prescription.prescriptionType %><br />
  Description: <%= @prescription.description %>
</p>

<%= link_to "Back", prescriptions_path%>

<%= link_to "Edit", edit_prescription_path(@prescription)%>